import { battleNumbers, bossConfig, interventionCards, investigatorConfig, skillConfig } from './config/battleConfig.js';

type Phase='intro'|'normal'|'intervention'|'victory'|'defeat';
type Fighter={id:string;name:string;role:string;hp:number;maxHp:number;energy:number;maxEnergy:number;dps:number;color:string;ticket:number;locked:number;shield:number;boost:number;healing:number};
const root=document.getElementById('root')!; const fmt=(n:number)=>Math.round(n).toLocaleString('zh-CN'); const pct=(v:number,m:number)=>`${Math.max(0,Math.min(100,v/m*100))}%`; const clock=(s:number)=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(Math.floor(s%60)).padStart(2,'0')}`;
let phase:Phase='intro', bossHp=bossConfig.maxHp, bossShield=0, fighters:Fighter[]=[], sanity=100, time=0, ticketCd=7, denyCd=10, shieldCd=13, vulnerable=0, seal=0, analyze=false, intervened=false, chosen='未执行', message='点击开始调查，进入雾港异常站台。', totalDamage=0, paused=false;
function base(){return investigatorConfig.map(i=>({...i,hp:Math.round(i.maxHp*.82),energy:78,maxEnergy:100,ticket:0,locked:0,shield:0,boost:0,healing:0}))}
function reset(){phase='normal';bossHp=bossConfig.maxHp;bossShield=0;fighters=base();sanity=100;time=0;ticketCd=7;denyCd=10;shieldCd=13;vulnerable=0;seal=0;analyze=false;intervened=false;chosen='未执行';message='自动调查开始：三名调查员正在压制异常。';totalDamage=0;paused=false;render()}
function choose(id:string){const c=interventionCards.find(x=>x.id===id)!;chosen=c.title;message=`已执行：${c.title}`;if(id==='seal')seal=8;if(id==='analyze')analyze=true;if(id==='drown'){sanity=Math.max(0,sanity-15);fighters.forEach(f=>f.boost=10)}phase='normal';render()}
function tick(){if(phase!=='normal'||paused)return;const dt=.1;time+=dt;vulnerable=Math.max(0,vulnerable-dt);seal=Math.max(0,seal-dt);fighters.forEach(f=>{f.ticket=Math.max(0,f.ticket-dt);f.locked=Math.max(0,f.locked-dt);f.boost=Math.max(0,f.boost-dt);f.healing=Math.max(0,f.healing-dt)});
 let dmg=fighters.reduce((s,f)=>s+(f.locked>0?0:f.dps)*(f.boost>0?1.5:1)*dt,0)*(vulnerable>0?1.35:1); if(bossShield>0){bossShield=Math.max(0,bossShield-dmg);dmg*=1-skillConfig.shieldDamageReduction;if(bossShield===0){vulnerable=5;message='闸门护盾破裂，Boss 易伤！'}} const old=bossHp;bossHp=Math.max(0,bossHp-dmg);totalDamage+=old-bossHp;
 if(!intervened&&bossHp<=bossConfig.maxHp*bossConfig.stageNode){phase='intervention';intervened=true;message='血量跌破 60%，调查干预已开启。'} if(bossHp<=0)phase='victory';
 ticketCd-=dt;if(ticketCd<=0){if(seal<=0){const f=fighters[Math.floor(Math.random()*fighters.length)];f.ticket=skillConfig.ticketDuration;message=`错误车票附着到${f.name}！`}ticketCd=skillConfig.ticketInterval}
 denyCd-=dt;if(denyCd<=0){const f=fighters.find(x=>x.ticket>0); if(f){f.locked=skillConfig.denyLockDuration;f.energy=Math.max(0,f.energy-12);sanity=Math.max(0,sanity-skillConfig.denySanityLoss);message=`${f.name}被拒绝通行锁定，理智受损！`}else{vulnerable=5;message='拒绝通行判定失败，Boss 进入易伤！'} denyCd=skillConfig.denyPassageInterval}
 shieldCd-=dt;if(intervened&&shieldCd<=0){bossShield=Math.round(bossConfig.shieldBase*(analyze?.4:1));analyze=false;message=`闸门护盾启动：${fmt(bossShield)}`;shieldCd=skillConfig.shieldInterval}
 fighters.forEach(f=>{if(f.ticket>0&&f.ticket<=dt+.001){f.energy=Math.max(0,f.energy-skillConfig.ticketEnergyLoss);sanity=Math.max(0,sanity-skillConfig.ticketSanityLoss)}}); if(Math.round(time*10)%60===0){fighters.forEach(f=>{f.hp=Math.min(f.maxHp,f.hp+skillConfig.pulseHeal);f.healing=1.2});const n=fighters.find(f=>f.ticket>0);if(n)n.ticket=0;sanity=Math.min(100,sanity+3)} if(sanity<=0)phase='defeat';render()}
function render(){if(phase==='intro'){root.innerHTML=`<main class="intro"><div class="intro-card"><p>阶段 0 可玩原型</p><h1>克鲁苏：无限循环</h1><p>单 Boss 自动调查验证</p><button id="start">开始调查</button></div></main>`;document.getElementById('start')!.onclick=reset;return} const result=phase==='victory'||phase==='defeat';root.innerHTML=`<main class="battle ${bossHp/bossConfig.maxHp<=.6?'phase2':''} ${result?'ended':''}">${header()}${stage()}${mechanics()}${bar()}${phase==='intervention'?intervention():''}${result?resultHtml():''}</main>`;bind()}
function header(){return `<section class="header"><div><b>${bossConfig.stageTitle}</b><span>${bossConfig.roundTitle}</span><label>理智 ${Math.round(sanity)} / 100</label><div class="bar sanity"><i style="width:${sanity}%"></i></div></div><div class="bossTop"><h2>${bossConfig.name}</h2><div class="bar hp"><i style="width:${pct(bossHp,bossConfig.maxHp)}"></i><em class="node"></em>${bossShield>0?`<strong style="width:${pct(bossShield,bossConfig.shieldBase)}"></strong>`:''}</div><p>${fmt(bossHp)} / ${fmt(bossConfig.maxHp)}</p></div><div class="actions"><button id="pause">${paused?'继续':'暂停'}</button><button id="exit">退出</button></div></section>`}
function stage(){return `<section class="stage"><div class="sign">雾港地铁异常站台<br/>请勿靠近闸机</div><div class="bossSilhouette"><div class="cap"></div><div class="head"></div><div class="body"></div><div class="gate"></div>${bossShield>0?`<div class="shieldAura">护盾 ${fmt(bossShield)}</div>`:''}</div><div class="statusRow">${bossShield>0?'<span>闸门护盾</span>':''}${vulnerable>0?`<span>易伤 ${vulnerable.toFixed(0)}秒</span>`:''}${seal>0?`<span>封印检票口 ${seal.toFixed(0)}秒</span>`:''}<span>错误车票</span></div>${message?`<div class="toast">${message}</div>`:''}</section>`}
function mechanics(){return `<section class="mechanics"><div><b>污染</b><p>当前污染：<em>错误车票</em> · 每 7 秒随机附着一名调查员</p></div><div><b>预警</b><p>下一技能：<em>${bossHp/bossConfig.maxHp<=.6?'闸门护盾':'拒绝通行'}</em> · ${Math.ceil(bossHp/bossConfig.maxHp<=.6?shieldCd:denyCd)} 秒后释放</p></div></section>`}
function bar(){return `<section class="investigators">${fighters.map(f=>`<article class="${f.locked>0?'locked':''}"><div class="avatar"><span>${f.name[0]}</span>${f.ticket>0?'<i>错误车票</i>':''}${f.healing>0?'<em>治疗</em>':''}</div><h3>${f.name}<small>${f.role}</small></h3><p>${Math.round(f.hp)} / ${f.maxHp}</p><div class="bar life"><i style="width:${pct(f.hp,f.maxHp)}"></i></div><p>${Math.round(f.energy)} / ${f.maxEnergy}</p><div class="bar energy"><i style="width:${pct(f.energy,f.maxEnergy)}"></i></div><div class="chips">${[['locked','技能封锁'],['ticket','错误车票'],['shield','护盾'],['boost','沉沦增伤']].filter(([k])=>(f as any)[k]>0).slice(0,2).map(([,v])=>`<span>${v}</span>`).join('')}</div></article>`).join('')}</section>`}
function intervention(){return `<section class="overlay intervention"><h2>调查干预</h2><p>选择本次对异常的处理方式</p>${interventionCards.map(c=>`<button data-card="${c.id}"><b>${c.title}</b><span>${c.desc}</span><em>${c.tag}</em></button>`).join('')}</section>`}
function resultHtml(){const ok=phase==='victory';return `<section class="overlay result"><h2>${ok?'调查成功':'调查失败'}</h2><p>${ok?'雾门收票人已完成收容记录':'失败原因：理智归零'}</p><dl><dt>剩余理智值</dt><dd>${Math.round(sanity)} / 100</dd><dt>总伤害</dt><dd>${fmt(totalDamage)}</dd><dt>战斗时长</dt><dd>${clock(time)}</dd><dt>本次干预</dt><dd>${chosen}</dd><dt>获得奖励</dt><dd>${ok?'记忆印记 ×1　回响数据 ×120':'无'}</dd></dl><div><button id="again">再次挑战</button><button id="home">返回观测所</button></div></section>`}
function bind(){document.getElementById('pause')?.addEventListener('click',()=>{paused=!paused;render()});document.getElementById('exit')?.addEventListener('click',()=>{phase='intro';render()});document.getElementById('again')?.addEventListener('click',reset);document.getElementById('home')?.addEventListener('click',()=>{phase='intro';render()});document.querySelectorAll('[data-card]').forEach(e=>e.addEventListener('click',()=>choose((e as HTMLElement).dataset.card!)))}
setInterval(tick,battleNumbers.tickMs);render();
